### ISSUE TITLE
iOS project with only one pair of .xcodeproj and .xcworkspace files asks to choose between those

### ISSUE THREAD

**Issue by vladimir-kotikov** [foreverest/mobile-center-cli#11]
Need to check if for example there is 'FooBar.xcworkspace' and 'FooBar.xcodeproj' files are found whether we should display both or we need to show only one of them

**Comment by vladimir-kotikov** [comment]
Here is a screenshot, demonstrating the issue (ran for https://github.com/MobileCenter/quickstart-ios)

![image](https://cloud.githubusercontent.com/assets/3857604/25651458/dff5337a-2feb-11e7-991b-eed173a0f241.png)

**Comment by denis-kudelin** [comment]
fixed
