### ISSUE TITLE
Branches with previews

### ISSUE THREAD

**Issue by foreverest** [foreverest/mobile-center-cli#18]
When we are selecting a branch to fetch project settings from, it might be useful to see the settings in the list. 

_e.g._

**Where do you want to get project settings from?**
 input manually...
\> master [app/release]
 dev [app/debug]

**Comment by denis-kudelin** [comment]
done

**Comment by foreverest** [comment]
@DenisKudelin it doesn't work in case of providing branch name via CLI argument

**Comment by denis-kudelin** [comment]
@foreverest fixed

**Comment by foreverest** [comment]
Commits:
278f945cad6e9fe63997d53d6b363019238e3f9e
929c76543a6d34ad5607b3e47e8dacd47b6a2423
81669df62c0ec64cd8227c0ce382ae73818c5bb7
