### ISSUE TITLE
[iOS] Incorrect SDK integration

### ISSUE THREAD

**Issue by foreverest** [foreverest/mobile-center-cli#30]
Incorrect result of SDK integration in AppDelegate.swift
![image](https://cloud.githubusercontent.com/assets/13933008/25948082/2abc3246-3663-11e7-923b-2d53e434d8c7.png)

To reproduce:
1) git clone https://github.com/macoscope/GrandCentralBoard.git
2) mobile-center init (x2)
![image](https://cloud.githubusercontent.com/assets/13933008/25947989/cb7bf3ac-3662-11e7-8222-fc03b0e780ce.png)

**Comment by denis-kudelin** [comment]
fixed
