### ISSUE TITLE
Adding SDK to iOS app second time with different set of components doesn't seem to work correctly

### ISSUE THREAD

**Issue by vladimir-kotikov** [foreverest/mobile-center-cli#7]
1. Run `mobile-center init` and choose to download new sample iOS ObjC app
2. Proceed with adding all 3 SDKs
3. Notice all 3 SDKs have been added successfully
4. Navigate to app deirectory and run integration again w/ another set of SDKs

Observe there are still all 3 SDKs are added to app files

**Comment by denis-kudelin** [comment]
fixed
