### ISSUE TITLE
`init` command should always use the latest versions of SDKs

### ISSUE THREAD

**Issue by vladimir-kotikov** [foreverest/mobile-center-cli#8]
Currently we're using hardcoded versions (e.g for Android we use 0.6.0). Ideally we need to fetch latest available version from libs' source and use it

- [ ] Android - check if it's feasible to get the latest artifact version from JCenter
- [ ] iOS - current integration instructions doesn't use a version number - to see if it's possible to reference specific version in podfile
  - [ ] use the same alghoritm as for Android

*OR*

- [ ] Check if it's possible just to reference the latest deps versions in *.gradle

**Comment by denis-kudelin** [comment]
done. It retrieves the latest version from github by specified platform.

> Check if it's possible just to reference the latest deps versions in *.gradle

not possible.
